version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
      - REACT_APP_API_URL=http://localhost:5001
    stdin_open: true
    tty: true

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend/src:/app/src
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - frontend